### ISSUE TITLE
LoginController里面登陆身份验证好像不可用啊

### ISSUE THREAD

**Issue by wrsxinlang** [uoyoCsharp/MiCake#8]
![image](https://user-images.githubusercontent.com/11786557/87874198-7f1f8300-c9fa-11ea-9428-44469f5ca3c4.png)

 [HttpGet]
        [Authorize]
        public List<string> GetInfo([CurrentUser] Guid userID)
        {
            var httpContext = _httpContextAccessor.HttpContext;
            var userInfo = httpContext?.User;

            var result = userInfo?.Claims.Select(s => s.Value).ToList();
            return result;
        }

我是这样解决的：
第一步：
 services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
                    .AddJwtBearer(o =>
                    {
                        o.TokenValidationParameters = new TokenValidationParameters
                        {
                            NameClaimType = JwtClaimTypes.Name,
                            RoleClaimType = JwtClaimTypes.Role,

                            ValidIssuer = new MiCakeJwtOptions().Issuer,
                            ValidAudience = new MiCakeJwtOptions().Audience,
                            IssuerSigningKey = new SymmetricSecurityKey(Encoding.ASCII.GetBytes("micake-256-bit-secret"))
        };
 });

第二步 ： app.UseAuthorization();

**Comment by uoyoCsharp** [comment]
@wrsxinlang  嗯，是的。在这个同项目一起的Sample例子中，其实没有对“JwtBearer”服务进行注册。您现在的做法是正确的。
而[CurrentUser]特性是对当前访问的用户ID进行匹配，在源码中您已经也有看到。
这个功能的演示代码在这个仓库中有使用到：https://github.com/uoyoCsharp/MiCake.Samples/tree/master/Experimental。
在博客园中有一篇文中我也有提到它：[《AspNetCore的身份验证》](https://www.cnblogs.com/uoyo/p/13209685.html)
